#!/bin/bash -x

#PLATFORM="28 233 31 35 37 25 51 53"
#PLATFORM="50 53"
PLATFORM="5x"
VTE_TARGET_PRE=/mnt/vte

KERNEL_DIR=/home/vobs/linux-2.6-imx

VTE_PARENT_DIR=/home/ltib2/vte_build/

VTE_DIR=${VTE_PARENT_DIR}vte

BUILD=y

export PATH=$PATH:/opt/freescale/usr/local/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/bin

RC=0

if [ $BUILD == "y" ]; then
rm -rf ${KERNEL_DIR}
tar xzvf /home/vobs/linux-2.6.35.3_wb.tar.gz -C /home/vobs/
mv /home/vobs/linux-2.6.35.3 ${KERNEL_DIR}

cd $VTE_PARENT_DIR

rm -rf vte

git clone git://10.192.225.222/vte
#git clone b20222@10.192.225.222:/home/git-repository/vte
cd vte


git checkout -b master origin/master
git pull

#git-checkout -b SDK_1.7_rel_RC5 origin/SDK_1.7_rel_RC5
#git-pull


chmod -R 777 .
fi

pt=$(echo $PLATFORM | grep 31 | wc -l)
if [ $pt = 1 ]; then
echo "make 31"
cd $KERNEL_DIR
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- mx3_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2


cd $VTE_DIR

source  mx31_3stack_config
./armconfig
#make apps || RC="31_apps $RC"
make
make vte || RC="31 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx31/testcases/bin/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx31/runtest/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx31/bin/
#sync to Wukong
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx31/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx31/bin
sudo scp -r runtest/* b17931@survivor:/rootfs/wb/vte_mx31/runtest/
fi


pt=$(echo $PLATFORM | grep 35 | wc -l)
if [ $pt = 1 ]; then
echo "make 35"
cd $KERNEL_DIR
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- mx3_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2


cd $VTE_DIR
make clean
source  mx35_3stack_config
./armconfig
make apps || RC="35_apps $RC"
make vte || RC="35 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx35/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx35/bin/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx35/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx35/bin
fi

pt=$(echo $PLATFORM | grep 37 | wc -l)
if [ $pt = 1 ]; then
echo "make 37"
cd $KERNEL_DIR
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- mx3_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2

cd $VTE_DIR
make clean
source  mx37_3stack_config
./armconfig
make apps || RC="37_apps $RC"
make vte || RC="37 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx37/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx37/bin/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx37/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx37/bin
fi

pt=$(echo $PLATFORM | grep 25| wc -l)
if [ $pt = 1 ]; then
echo "make 25"
cd $KERNEL_DIR
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx25_3stack_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2


cd $VTE_DIR
make clean
source  mx25_3stack_config
./armconfig
#make apps || RC="25_apps $RC"
make vte || RC="25 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx25/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx25/bin/
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx25/bin
fi

pt=$(echo $PLATFORM | grep 23 | wc -l)
if [ $pt = 1 ]; then
echo "make 23"
cd $KERNEL_DIR
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx23evk_defconfig 
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2


cd $VTE_DIR
make clean
source mx233_armadillo_config
./armconfig
#make apps || RC="23_apps $RC"
make vte || RC="23 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx233/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx233/bin/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx233/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx233/bin
fi

pt=$(echo $PLATFORM | grep 51 | wc -l)
if [ $pt = 1 ]; then
echo "make 51"
cd $KERNEL_DIR
make distclean
#make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx51_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx5_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2


cd $VTE_DIR
make clean
source  mx5x_evk_config
./armconfig
#make apps || RC="51_apps $RC"
make vte || RC="51 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx51/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx51/bin/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx51/runtest/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx51/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx51/bin
sudo scp -r runtest/* b17931@survivor:/rootfs/wb/vte_mx51/runtest
fi

pt=$(echo $PLATFORM | grep 28 | wc -l)
if [ $pt = 1 ]; then
echo "make 28"
#cd /home/vobs
#git clone ssh://sw-git01-tx30.am.freescale.net/git/sw_git/repos/linux-2.6-testbuild.git
#mv linux-2.6-testbuild linux-2.6-mx28
#cd linux-2.6-mx28
#git checkout --track -b imx_2.6.31_mx28_precode origin/imx_2.6.31_mx28_precode
cd ${KERNEL_DIR}
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx28evk_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2

cd $VTE_DIR
make clean
source mx28_evk_config
./armconfig
#make apps || RC="28_apps $RC"
make vte || rc="28 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx28/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx28/bin/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx28/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx28/bin
fi

pt=$(echo $PLATFORM | grep 53 | wc -l)
if [ $pt = 1 ]; then
echo "make 53"
#cd /home/vobs
#git clone ssh://sw-git01-tx30.am.freescale.net/git/sw_git/repos/linux-2.6-testbuild.git
#mv linux-2.6-testbuild linux-2.6-mx28
#cd linux-2.6-mx28
#git checkout --track -b imx_2.6.31_mx28_precode origin/imx_2.6.31_mx28_precode


cd ${KERNEL_DIR}
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx5_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2

cd $VTE_DIR
make clean
source mx53_evk_config
./armconfig
#make apps || RC="53_apps $RC"
make vte || rc="53 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx53/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx53/bin/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx53/runtest/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx53/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx53/bin
sudo scp -r runtest/* b17931@survivor:/rootfs/wb/vte_mx53/runtest/
fi


pt=$(echo $PLATFORM | grep 50 | wc -l)
if [ $pt = 1 ]; then
echo "make 50"
#cd /home/vobs
#git clone ssh://sw-git01-tx30.am.freescale.net/git/sw_git/repos/linux-2.6-testbuild.git
#mv linux-2.6-testbuild linux-2.6-mx28
#cd linux-2.6-mx28
#git checkout --track -b imx_2.6.31_mx28_precode origin/imx_2.6.31_mx28_precode


cd ${KERNEL_DIR}
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx5_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2

cd $VTE_DIR
make clean
source mx5x_evk_config
./armconfig
#make apps || RC="50_apps $RC"
make vte || rc="50 $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx50/testcases/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx50/bin/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx50/runtest/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx53/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx53/bin
sudo scp -r runtest/* b17931@survivor:/rootfs/wb/vte_mx53/runtest/
fi

pt=$(echo $PLATFORM | grep 5x | wc -l)
if [ $pt = 1 ]; then
echo "make 5x"

cd ${KERNEL_DIR}
make distclean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- imx5_defconfig
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- -j 2

cd $VTE_DIR
make clean
source mx5x_evk_config
./armconfig
make apps || RC="5x_apps $RC"
make
make install
make vte || rc="5x $RC"
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx50/testcases/bin/
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx51/testcases/bin/
sudo cp -a testcases/bin/* ${VTE_TARGET_PRE}/vte_mx53/testcases/bin/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx53/runtest/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx50/runtest/
sudo cp -a runtest/* ${VTE_TARGET_PRE}/vte_mx51/runtest/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx50/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx51/bin/
sudo cp -a bin/* ${VTE_TARGET_PRE}/vte_mx53/bin/
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx51/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx51/bin
sudo scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx53/testcases/bin
sudo scp -r bin/* b17931@survivor:/rootfs/wb/vte_mx53/bin

#50 not in xiaotian
#scp -r testcases/bin/* b17931@survivor:/rootfs/wb/vte_mx53/testcases/bin
fi

#deply debain packages
if [ -e /mnt/nfs_root/pkg_handle.sh ]; then
sudo ROOTFS=/mnt/nfs_root/ubuntu_10.10 /mnt/nfs_root/pkg_handle.sh remove /mnt/nfs_root/debains
sudo ROOTFS=/mnt/nfs_root/ubuntu10.10 /mnt/nfs_root/pkg_handle.sh install /mnt/nfs_root/debains
fi

echo $RC
echo "VTE build OK" | mutt -s "VTE build is OK" \
b20222@freescale.com 

if [ "$RC" = "0" ]; then

echo build success!!

else

echo build Fail $RC!

fi

