#!/bin/sh
# Program:
# 	mount the mmc disk into /mnt/mmc0~n
# prerequisite:
#   all mmc kernel driver should inserted.
#   MMC card insert in
# History:
# 2008/07/02	Hake First release

#check the /proc/partition
echo please make sure your insmod the mmc card driver
echo please make sure the mmc card is inserted


wait 3

PROC=$(mount | awk '{print $1}' | grep proc)
MMCMAJOR=179
MMCBLK=0

echo make sure MMC major number is $MMCMAJOR

if [ -z $PROC ]
then
mount proc /proc -t proc
fi

wait 5

DNAMES=$(cat /proc/partitions | awk -v mj="$MMCMAJOR" -v mr="$MMCBLK" '{if($1 == mj && $2 != mr) print $4}')

echo $DNAMES


for i in $DNAMES
do
   ISMOUNT=$(mount | grep $i| awk '{print $1}')
   if [ -z $ISMOUNT ]
   then
     if [ -e /dev/$PNAME ]
     then
       echo device node exist
     else
       mknode /dev/$i
     fi 
     mkdir -p /mnt/mmc/$i
     FILESYS=$(fsck -T -N /dev/$i)
     CHECKDOS=$(echo $FILESYS | grep msdos)
     if [ "$CHECKDOS" ]
     then
       mount -t vfat /dev/$i /mnt/mmc/$i
     else
       CHECKEXT2=$(echo $FILESYS | grep ext2)
       if [ "$CHECKEXT2" ]
       then
         mount -t ext2 /dev/$i /mnt/mmc/$i
       else
         echo no file system support for $i
       fi 
     fi
   fi
done


mount

